language: generic
os:
- linux
- osx
env:
  matrix:
  - PYTHON="3.8"
  - PYTHON="3.7"
  - PYTHON="3.6"
jobs:
  include:
  - stage: lint
    os: linux
    script:
    - pip install flake8
    - make lint

  - stage: deploy
    if: tag =~ v.*$
    script: skip
    os: linux
    deploy:
      on:
        all_branches: true
      provider: pypi
      user: mcflugen
      password:
        secure: SUvXMtJt/BrlKMBU1WDp9yQSm18yfjvPr7p0A5hjRykoKEtQ4kLbIuUXRLHyb9lnbuBen00oaCyJIjoYWWGbt0mcSLz39CMAgid1NsNMCq780c41IF2+Wm3HnUb9Ifm+38wNP/sqieGb6nm2Pq5sBHfeaB5+iCSup+fysOg6SvrCtxwCReNC0FeGD3dQ09XL6sk7rzmX78a5XXSSip5b/N0SAG9SgCiwkmCky4rZlZNWxBzrI5Gg0cYBNtw9HKCOZ/7xn3KvAdhz6i1t9sSzEIf6AFBSFX9D2/yratk7n60z3Os9sTX0Wve4wsk1+cYOtfe6x27/lN2Z0dgTAtY75DstCP5yIJeoYiFZaMTdg2mpY875xMPK95P2JYplyPdmTZPNaeJhR5qNwfn4LX97uK9sQ7lMm1U4qKxINMGd0ysacqnvvh0ndZs+hGudRVhfKM9Q4y+Gz5Snj6oLhP3XroB0WECJnj9DpOHpnCYbFFC0eOV2jUeqR4MMKbuAnuccdEqbaNdVpgKvL6OgWJrfpcHi1rcgLtZQNF4cBetWcqLet6JU/zrJcls2NXpe3LQKWpdxtXjN+8jqL5HOqEVtMc6Vekj3P0XYWsbfKAutsqKBO8NYIuSPsUaO0+qzVCWVV0URxZg0R/RoMHlolPQyz7OiHRECietiWV6wbYO0NZ8=

before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    curl -L https://micromamba.snakepit.net/api/micromamba/osx-64/latest | tar -xvj bin/micromamba
  else
    curl -L https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
  fi
- ./bin/micromamba shell init -s bash -p ~/micromamba
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    source $HOME/.bash_profile
  else
    source $HOME/.bashrc
  fi
- micromamba activate
- micromamba install python=$PYTHON pip mamba --yes -c conda-forge
install:
- pip install -e .
script:
- pip install -r requirements-testing.txt
- pytest --cov=model_metadata --cov-report=xml:$(pwd)/coverage.xml -vvv
- mmd --help
- mmd --version
- mmd find --help
- mmd query --help
- mmd stage --help
after_success: coveralls
