{% set data = load_setup_py_data() %}

package:
  name: model_metadata
  version: {{ data.get('version') }}

source:
  path: ..

requirements:
  build:
    - python
    - pip
  run:
    - python
    - packaging
    - pyyaml
    - six
    - jinja2
    - scripting
    - binaryornot

test:
  commands:
    - mmd --help
    - mmd-dump --help
    - mmd-find --help
    - mmd-install --help
    - mmd-query --help
    - mmd-stage --help

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - mmd = model_metadata.cli.main:main
    - mmd-dump = model_metadata.cli.main_dump:main
    - mmd-find = model_metadata.cli.main_find:main
    - mmd-install = model_metadata.cli.main_install:main
    - mmd-query = model_metadata.cli.main_query:main
    - mmd-stage = model_metadata.cli.main_stage:main

about:
  home: http://github.com/csdms/model_metadata
  license: MIT
  license_file: LICENSE
  summary: The CSDMS Python tools for model metadata
  description: |
    Tools for working with model metadata and staging model simulations.
  doc_url: http://model_metadata.readthedocs.org
  dev_url: http://github.com/csdms/model_metadata
