{% set name = "model_metadata" %}
{% set version = "0.1" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

requirements:
  build:
    - python
    - packaging
    - setuptools
    - pyyaml
    - six
    - jinja2
    - scripting
    - packaging
    - binaryornot

  run:
    - python
    - packaging
    - numpy
    - pyyaml
    - six
    - jinja2
    - scripting
    - packaging
    - binaryornot

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs model_metadata --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

about:
  home: http://github.com/csdms/model_metadata
  license: MIT
  license_file: LICENSE
  summary: The CSDMS Python tools for model metadata
  description: |
    Tools for working with model metadata and staging model simulations.
  doc_url: http://model_metadata.readthedocs.org
  dev_url: http://github.com/csdms/model_metadata
